name: Request Deployment - PyDM Display

on:
  workflow_dispatch:
    inputs:
      deploy_to_dev:
        type: boolean
      deploy_to_lcls:
        type: boolean
      deploy_to_facet:
        type: boolean
      deploy_to_testfac:
        type: boolean
      deploy_to_sandbox:
        type: boolean
      tag:
        required: true
        type: string

jobs:
  deploy:
    uses: ad-build-test/build-system-playbooks/.github/workflows/request-deployment.yml@main
    with:
      deploy_to_dev: ${{ inputs.deploy_to_dev }}
      deploy_to_lcls: ${{ inputs.deploy_to_lcls }}
      deploy_to_facet: ${{ inputs.deploy_to_facet }}
      deploy_to_testfac: ${{ inputs.deploy_to_testfac }}
      deploy_to_sandbox: ${{ inputs.deploy_to_sandbox }}
      tag: ${{ inputs.tag }}
      deployment_type: 'pydm'
